### PR TITLE
Add more Python package version requirements

### PR DESCRIPTION
**Pull request by christabella**
Got some errors when doing a fresh `conda` install with just the given requirements; had to downgrade both `numpy` and `scipy` versions to get the Omniglot image preprocessing (`python utils.py`) running.

Figured a good numpy version from a [scikit-image comment](https://github.com/scikit-image/scikit-image/issues/3586#issuecomment-455190679).
Guessed the scipy version by looking at the [releases](https://github.com/scipy/scipy/releases) and from https://stackoverflow.com/questions/56204985/how-to-fix-scipy-misc-has-no-attribute-imresize.

These versions might not be the same as those used in the original environment; so it might be an even better idea to drop in the output from either `conda list` or `pip list` in a `requirements.txt`:
```
conda list --export > requirements.txt
```
or
```
pip freeze > requirements.txt
```
And include some instructions in the README like:
```
conda create --name <envname> --file requirements.txt
```
or
```
pip install -r requirements.txt
```

### CODE REVIEW

**Comment by IraKorshunova** [comment]
Thanks for pointing this out! I checked my versions of numpy and scipy and those were 1.14.2 and 1.0.0. Could you please confirm that you got everything running with the versions from your pr? I'll merge it then.

**Comment by christabella** [comment]
I see, thanks for checking! I think it's best to use the versions you used :) 

I haven't been able to get the training running, likely due to a Python or CUDA version mismatch. May I know which Python and CUDA you are using? (I'm on 3.6 and 10.1 respectively)

**Comment by IraKorshunova** [comment]
I had cuda 9. My guess is that cuda 10 might be too new for tensorflow 1.7. Please let me know if you get it to work or if I can help somehow.

**Comment by christabella** [comment]
Thanks a lot for the info!

**Pull request merged**
